### ISSUE TITLE
Hints or best practices for filtering in documentation

### ISSUE THREAD

**Issue by rudyryk** [getlogbook/logbook#126]
I'm diving in to Logbook lib and I found it confusing, that there are no examples or hints for records filtering (or they are hard to found?).

Also it seems that channel names should be just descriptive and human readable, as said in `Logger` class docs: http://pythonhosted.org/Logbook/api/base.html
> Names used by logbook should be descriptive and are intended for user display, **not for filtering**.

But the other part of docs says, on the same page for `LogRecord.channel`: http://pythonhosted.org/Logbook/api/base.html#logbook.LogRecord
> the name of the logger that created it or any other textual channel description. This is a descriptive name and **can be used for filtering**.

So, are there any real practices with that? How is it intended to be finally by design? I think I will be able to provide some examples of 'real usage', but I need first to understand that by myself :)

Thank you for the Logbook!

**Comment by brainstorm** [comment]
@rudyryk, happy to see your discussion/ideas pointed out in the documentation as changes. Feel free to edit the docs as you think would fit better the understanding of (new) developers and we can take it from there :)
