### ISSUE TITLE
Documentation and/or enhancements for package developers.

### ISSUE THREAD

**Issue by RazerM** [getlogbook/logbook#159]
It would be interesting to see a proposed implementation for developers to use logbook for their own modules.

In the past I have used a modulename/log.py file which instantiates a Logger instance (disabled by default), with the other python files doing `from .log import logger`.

For example, I'm trying to think how [sqlalchemy would use Logbook rather than logging](http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#configuring-logging), since they make use of nested loggers quite well.

Would the logbook way be to have a Logger instance in sqlalchemy/engine and sqlalchemy/pool?

**Comment by vmalloc** [comment]
I think the real question is *why* nested loggers are used. It's usually not only to organize the names better - it's to reuse the handlers on the parent logger. 

Logbook does not associate handlers for specific loggers, but rather chooses a centralized handler stack with multiple loggers writing to the same stack...
