### ISSUE TITLE
Fix Appveyor deployment

### ISSUE THREAD

**Issue by vmalloc** [getlogbook/logbook#160]
(Moved from https://github.com/mitsuhiko/logbook/commit/c988651991ae9fda44a680bff07ba19ee0bd8091#commitcomment-14210964)

**Comment by vmalloc** [comment]
So @RazerM how does Appveyor deduce the `1.0.4` build version? It looks like other than that the build was uploaded

**Comment by RazerM** [comment]
It's just AppVeyor's incremental number each time it builds a commit.

![capture](https://cloud.githubusercontent.com/assets/1337586/10969937/9dd9fb6a-83cb-11e5-8e14-0e92e43361eb.PNG)

**Comment by RazerM** [comment]
If you tag a commit then push to GitHub, AppVeyor will use that

**Comment by vmalloc** [comment]
Ok. So it should be solved for the next release then.

**Comment by RazerM** [comment]
I'd like to see wheels for 0.11.3 on PyPI, would it be possible to do so? You'd just need to change the version number to 0.11.3 on your test branch, push, then download the wheels from appveyor (or whatever draft release it makes since the files are all in one place) then run `twine upload dist/*`

**Comment by vmalloc** [comment]
https://github.com/getlogbook/logbook/releases/tag/0.11.3, hopefully I'm not missing anything

**Comment by RazerM** [comment]
I'm not sure about the `post20151107` part, do you know why that was added?

Also can you post the URL to where AppVeyor moved to?

**Comment by vmalloc** [comment]
I'm not sure about either of those questions. What do you mean moved? We changed the repository name to getlogbook/logbook if that's what you mean

**Comment by RazerM** [comment]
Sorry I had the URL wrong. Can you link to AppVeyor in the README?

I don't know why the wheel version number includes a [post release number](https://www.python.org/dev/peps/pep-0440/#post-releases), since the setup.py just had '0.11.3'.

Can you [upload the wheels to PyPI](http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#upload-your-distributions)?

**Comment by vmalloc** [comment]
The post is probably because I ran the job manually.

Isn't there a way to upload to pypi without manual intervention? I really want to reduce the number of manual steps needed...

**Comment by RazerM** [comment]
We could upload the wheels from AppVeyor to PyPI when `APPVEYOR_REPO_TAG=true`.

We'd use `twine upload -u %PYPI_USERNAME% -p %PYPI_PASSWORD dist/*.whl`, where the `PYPI_` variables are secure environment variables.

**Comment by RazerM** [comment]
@vmalloc So redis server isn't starting on AppVeyor for some reason.
I propose 'redis' is removed from [this line](https://github.com/getlogbook/logbook/blob/b2e5b5acd28c891fbdc3bb78631cf7b1cb3ca275/.appveyor/prepare.bat#L6) to force the redis tests to skip.

If the build works, then 12.3 tag can be pushed to hopefully get the wheels onto PyPI?

**Comment by vmalloc** [comment]
yes. Will try it soon.

**Comment by vmalloc** [comment]
Pushed 0365c7b. Now the long, excruciating wait for the AppVeyor build to finish :cry:

**Comment by RazerM** [comment]
excruciating indeed! Looking good so far at least...

**Comment by RazerM** [comment]
Built successfully apart from the same Python 3.2 errors that keep happening (which I've ignored until #170 is decided).

**Comment by vmalloc** [comment]
I'm bumping 0.12.3, hopefully now the setup will be working as expected.

**Comment by RazerM** [comment]
I think this can be closed now. Thanks for bearing with me while everything got set up!

**Comment by vmalloc** [comment]
@RazerM no problem - it's you we should thank for taking the time to improve our compatibility coverage! keep up the good work!
