### ISSUE TITLE
Drop support for Python 3.2

### ISSUE THREAD

**Issue by vmalloc** [getlogbook/logbook#170]

**Comment by vmalloc** [comment]
@rnortman as all major distros now offer Python 3.3 and/or 3.4 by default (Even CentOS 6), do you have a strong objection to dropping 3.2 support? I'm asking because you put some effort into supporting it.

**Comment by rnortman** [comment]
@vmalloc I don't object strongly enough to put in the work to maintain it myself, which is probably all the answer you need, but thanks for asking.  I know that a lot of production environments are stuck on older distros (like Debian Squeeze LTS or Wheezy), but this no longer affects me directly.

**Comment by mitsuhiko** [comment]
To make the decision easier: these are the download numbers for markupsafe by Python version in beginning of 2015: http://i.imgur.com/T1Z7VRW.png - (Which supports 3.2 on the non latest release)
