### ISSUE TITLE
Binary eggs on PyPI

### ISSUE THREAD

**Issue by RazerM** [getlogbook/logbook#173]
There are eggs on [PyPI for v0.12.3](https://pypi.python.org/pypi/Logbook/0.12.3) made for linux which enclude `_speedups.so`. Is this not a problem since Python is compiled differently on different versions of Linux?

From [Python on Wheels](http://lucumr.pocoo.org/2014/1/27/python-on-wheels/):
> Linux binary distributions are still not an option for most people because of two basic problems: Python itself being compiled in different forms on Linux and modules being linked against different system libraries. The first problem is caused by Python 2 coming in two flavours that are both incompatible to each other: UCS2 Pythons and UCS4 Pythons. Depending on which mode Python is compiled with the ABI looks different.

**Comment by vmalloc** [comment]
The main problem is that we don't want to require people to install `python-dev` on their platform, and still be able to get the benefits of speedups, so eggs include it (while sdist does not). 

In theory there could be issues, but many binary eggs out there contain shared objects without real issues. Did you encounter any real issues?

**Comment by mitsuhiko** [comment]
How did you even manage to get a wheel up there?  PyPI should actively block you from releasing binary wheels for Linux as they do not work.

**Comment by mitsuhiko** [comment]
Oh. Those are not actually wheels but eggs. But they do not work either, same problem. I guess pypi just permits them because nobody uses those any more.

**Comment by vmalloc** [comment]
I will remove the pre-deploy step I added - that's what causes it.

**Comment by vmalloc** [comment]
Ok, the confusion was on me. I mistook the building we did for speedups.so so that it would build _speedups.c in the process, and I got confused thinking that it's the `.so` we should upload. I removed uploading the bdist_egg so the next bump would only upload an sdist.

**Comment by RazerM** [comment]
@vmalloc The eggs should probably be removed from PyPI, no?

**Comment by vmalloc** [comment]
yup. I just removed them. Thanks for the heads up.
