### ISSUE TITLE
Is there a way to fix the width of a certain element in the format_string?

### ISSUE THREAD

**Issue by chishaku** [getlogbook/logbook#181]
In `logging`, I was able to do something like this `"%(foo)8s" % {'foo': 'bar'}`.

**Comment by vmalloc** [comment]
Of course!

For instance: `logbook.info('{:8}', 'argument)`. Logbook uses `str.format` which has a very extensive feature set. Check out Python's documentation for more usage examples (for instance, `{:>8}` will right-justify)

**Comment by vmalloc** [comment]
Almost forgot - but I wrote a cheat sheet for Dash a while back about format strings. Check it out here: https://github.com/vmalloc/dash_pyfmt/blob/master/cheats.yml

**Comment by chishaku** [comment]
@vmalloc Thanks!
