### ISSUE TITLE
SyslogHandler didn't work in Windows.

### ISSUE THREAD

**Issue by lanfon72** [getlogbook/logbook#186]
hi there,
I just try to follow [register handler](http://logbook.readthedocs.org/en/stable/quickstart.html#registering-handlers) step, 
But I got an error `AttributeError: module 'socket' has no attribute 'AF_UNIX'`.

(I'm not sure that SyslogHandler is supported in Windows or not, Because the sample is in Quickstart, and I think it is for some stupid guys like me :joy_cat: )

**Comment by vmalloc** [comment]
Syslog isn't supported on windows.

**Comment by lanfon72** [comment]
thanks, I will try another handler.

**Comment by vmalloc** [comment]
Perhaps a part of the confusion is the term `syslog` - it is not just short for `system log` -- it is a known UNIX facility, allowing unified logging.
