### ISSUE TITLE
speedups.so is not compiled on 0.12.4

### ISSUE THREAD

**Issue by wiggin15** [getlogbook/logbook#188]
With 0.12.3, _speedups.so extension is compiled:

    root@host-ci050 (Ubuntu 14.04) ➜  ~  easy_install Logbook==0.12.3
    Searching for Logbook==0.12.3
    Reading https://pypi.infinidat.com/simple/Logbook/
    Best match: Logbook 0.12.3
    Downloading https://pypi.infinidat.com/media/dists/Logbook-0.12.3.tar.gz#md5=97cfae1ff30b408ef984375712cfea1c
    Processing Logbook-0.12.3.tar.gz
    Writing /tmp/easy_install-Gy6HhX/Logbook-0.12.3/setup.cfg
    Running Logbook-0.12.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Gy6HhX/Logbook-0.12.3/egg-dist-tmp-oq5LBg
    creating /root/python/lib/python2.7/site-packages/Logbook-0.12.3-py2.7-linux-i686.egg
    Extracting Logbook-0.12.3-py2.7-linux-i686.egg to /root/python/lib/python2.7/site-packages
    Adding Logbook 0.12.3 to easy-install.pth file

    Installed /root/python/lib/python2.7/site-packages/Logbook-0.12.3-py2.7-linux-i686.egg
    Processing dependencies for Logbook==0.12.3
    Finished processing dependencies for Logbook==0.12.3
    root@host-ci050 (Ubuntu 14.04) ➜  ~  ls -la /root/python/lib/python2.7/site-packages/Logbook-0.12.3-py2.7-linux-i686.egg/logbook/_speedups.so
    -rwxr-xr-x 1 root root 302931 Jan 11 12:25 /root/python/lib/python2.7/site-packages/Logbook-0.12.3-py2.7-linux-i686.egg/logbook/_speedups.so

With 0.12.4 we can see a warning, and the extension is not built (the warning doesn't show when using 'pip' but it still doesn't work)

    root@host-ci050 (Ubuntu 14.04) ➜  ~  easy_install -U Logbook
    Searching for Logbook
    Reading https://pypi.infinidat.com/simple/Logbook/
    Best match: Logbook 0.12.4
    Downloading https://pypi.infinidat.com/media/dists/Logbook-0.12.4.tar.gz#md5=fb75ef285d48997fcaea70df8fbb9406
    Processing Logbook-0.12.4.tar.gz
    Writing /tmp/easy_install-sxrVuu/Logbook-0.12.4/setup.cfg
    Running Logbook-0.12.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sxrVuu/Logbook-0.12.4/egg-dist-tmp-s6N9U8
    warning: no files found matching 'logbook/_speedups.c'
    creating /root/python/lib/python2.7/site-packages/Logbook-0.12.4-py2.7.egg
    Extracting Logbook-0.12.4-py2.7.egg to /root/python/lib/python2.7/site-packages
    Removing Logbook 0.12.3 from easy-install.pth file
    Adding Logbook 0.12.4 to easy-install.pth file

    Installed /root/python/lib/python2.7/site-packages/Logbook-0.12.4-py2.7.egg
    Processing dependencies for Logbook
    Finished processing dependencies for Logbook
    root@host-ci050 (Ubuntu 14.04) ➜  ~  ls -la /root/python/lib/python2.7/site-packages/Logbook-0.12.4-py2.7.egg/logbook/_speedups.so
    ls: cannot access /root/python/lib/python2.7/site-packages/Logbook-0.12.4-py2.7.egg/logbook/_speedups.so: No such file or directory

**Comment by RazerM** [comment]
(@vmalloc: Unrelated to this bug, I just noticed that #173 happened again for 0.12.4, the binary eggs should be removed from PyPI)

**Comment by RazerM** [comment]
@wiggin15 Can you run `pip install -v Logbook` and paste the log?

**Comment by wiggin15** [comment]
Sorry - it looks like we had a broken mirror of the sdist which did not include the file _speedups.c file. I see that it exists on PyPI correctly. I don't know how it got there.
