### ISSUE TITLE
logged_if_slow API

### ISSUE THREAD

**Issue by RazerM** [getlogbook/logbook#193]
I think the logged_if_slow API is a bit awkard. I think we should change it for v1.0.

Current API:
```
def logged_if_slow(message, threshold=1, func=logbook_debug, args=None, kwargs=None)
```

Problems:
- Always uses default logger
- Have to pass log function, why not a level?
- args and kwargs are normal parameters (rather than `*args`, `**kwargs`).

Proposed API:
```
def logged_if_slow(*args, **kwargs):
    threshold = kwargs.pop('threshold', 1)
    logger = kwargs.pop('logger', _default_logger)
    level = kwargs.pop('level', logbook.DEBUG)
    # Context manager would call:
    logger.log(level, *args, **kwargs)
```

Then the context manager can simply call

```
logger.log(level, *args, **kwargs)
```

Also: are there valid reasons to use threading and events to handle the threshold rather than just storing a `time.time()` value and comparing in `__exit__`? I don't know how the threading timeout works, so I'm just curious about the implementation!

**Comment by vmalloc** [comment]
I'm not sure what you're asking - where did the `message` argument go in your proposal?

The idea behind using threads is to not be affected if the current thread is blocked on a long operation...

**Comment by RazerM** [comment]
`message` would be passed to `logger.log` as part of `*args`, just like the normal log methods. I've just edited the original message because I had `*args` in the wrong place.

**Comment by vmalloc** [comment]
Your proposed syntax is illegal in Python 2, and would only work with using a single `*` in Python 3, so I'm not sure what you have in mind exactly...

**Comment by RazerM** [comment]
Sorry, the proposal is now valid syntax...

**Comment by vmalloc** [comment]
Ok, seems reasonable. I prefer to have an optional `func` to preserve the current behavior and not break client code at least. Also - it must use threads IMO.
