### ISSUE TITLE
publish updated docs to docs site

### ISSUE THREAD

**Issue by jab** [getlogbook/logbook#209]
https://pythonhosted.org/Logbook/ still shows docs for version 0.11.3-dev.

**Comment by vmalloc** [comment]
Unfortunately that's not under my control. There doesn't seem to be a way of removing docs from that URL and/or to redirect to the true doc website (https://logbook.readthedocs.io)...

I opened an issue to pypi about it, but they don't seem to be responding...

**Comment by vmalloc** [comment]
Strike that! I managed to upload a redirection script eventually!

Closing this now.

**Comment by jab** [comment]
Nice, thanks!
