### ISSUE TITLE
publish latest release notes

### ISSUE THREAD

**Issue by jab** [getlogbook/logbook#210]
The most recent release shown at https://github.com/getlogbook/logbook/releases is 0.11.3. Ideally there'd be an automated way to get the release notes from https://github.com/getlogbook/logbook/blob/master/CHANGES into there, but in the meantime anyone with the commit bit could copy/paste them.

**Comment by vmalloc** [comment]
I published 1.0.0. I will try to look into an automated way of doing it, but for now it's good.

Thanks for turning my attention to it!

**Comment by jab** [comment]
Thanks!
