### ISSUE TITLE
Cannot receive pushover messages logged at the end of script

### ISSUE THREAD

**Issue by kongscn** [getlogbook/logbook#219]
I'm using `logbook.notifiers.PushoverHandler` to push some important messages.
The log at the very end seems work partially: the messages are printed and wrote to logging file, but it does not push to pushover.net. If I put something like `time.sleep` behind, it works fine. It seems that  the program is not waiting for the time consuming `ThreadedWrapperHandler`s to finish? How can I cope with this?

**Comment by vmalloc** [comment]
From the looks of it, `ThreadedWrapperHandler.close` waits for the thread to actually finish, so I guess your app needs to call that before exiting...

**Comment by kongscn** [comment]
Thank you @vmalloc . Directly using  `PushoverHandler` works just fine, I think the `ThreadedWrapperHandlers` is not expected to use like this. Closing.
