### ISSUE TITLE
Trove classifiers are missing from PyPI page

### ISSUE THREAD

**Issue by cclauss** [getlogbook/logbook#224]
https://github.com/getlogbook/logbook/blob/master/setup.py#L199-L204 shows that Logbook supports both Python 2 and Python 3 but those trove classifiers are missing from https://pypi.python.org/pypi/Logbook so software can not automatically figure out which versions of Python Logbook supports.

**Comment by vmalloc** [comment]
Fixed. Thanks for reporting!
