### ISSUE TITLE
searching through a log file

### ISSUE THREAD

**Issue by jeffreyscottgraham** [getlogbook/logbook#229]
Hello,

I have an app in which I created a handful of separate logbook log files in different subprocesses.

After joining these subprocesses I need to search through the logfiles for an ordered list of strings.
Q1: are the subprocess logfiles still opened? If so, can I still open them again for reading? If not, how
       do I close the logbook files so I can re-open then using normal python file operations?
Q2: does logbook support a search mechanism (not a filter!) ? If so, can this be a regex?

Thanks!

**Comment by vmalloc** [comment]
Logbook does not support searching.

Files opened for append can (at least on UNIX-derived systems) be opened
for reading in parallel.
