### ISSUE TITLE
"Stale file handle" OSError received when logging with a RotatingFileHandler into an NFS folder

### ISSUE THREAD

**Issue by eli-b** [getlogbook/logbook#243]
Here's the traceback I got:
```
Traceback (most recent call last):
  File "/home/myvenv/lib/python3.4/site-packages/logbook/handlers.py", line 213, in handle
    self.emit(record)
  File "/home/myvenv/lib/python3.4/site-packages/logbook/handlers.py", line 761, in emit
    if self.should_rollover(record, len(msg)):
  File "/home/myvenv/lib/python3.4/site-packages/logbook/handlers.py", line 739, in should_rollover
    self.stream.seek(0, 2)
OSError: [Errno 116] Stale file handle
Logged from file /home/path/to/my/project/myfile.py, line 123 (a line where I called logger.info)
```

If I understand correctly, this error is raised when an NFS client tries to e.g. read (or seek, in this case) a file that was deleted or moved, but the client still holds a handle to it.

I'm reasonably sure nobody deleted my log file while my program was running. I suspected logging in a different thread (greenlet, in my case) caused a log rollover, making this thread's file handle stale, but it looks like RotatingFileHandler is properly protected with a lock. Also, I don't think I generated long enough log messages to warrant a rotation.

I'm still using logbook version 1.0.0, but the changelog doesn't mention this was fixed in version 1.1.0.

**Comment by vmalloc** [comment]
@eli-b AFAIK the stale handle-type issues only happen when handles are shared across processes. Within a single process, the file descriptor, if closed, should yield a specific errno (EBADF) and cannot result in stale file handles. 

This can, however, happen with mounts over unstable network connections. 

If you can produce a more concise scenario to reproduce this, I can investigate further.

**Comment by eli-b** [comment]
Thanks. This has only happened once for me and the code that got this error is used fairly often. I don't have a way to reproduce the error at the moment.

My local network is sometimes unstable, so that was probably the cause.

**Comment by vmalloc** [comment]
@eli-b this is a reasonable explanation. In any case if you hit it again and can reproduce, feel free to reopen.
