### ISSUE TITLE
PyCharm debugger

### ISSUE THREAD

**Issue by runflowcode** [getlogbook/logbook#249]
Hi,

I am trying to understand what Logbook is doing in the background when it is first loaded. There's something that it is doing causing PyCharm to wait forever. The debugger window is showing 'Collection data..' and runtime information is never shown.

This is not a bug or an issue. It's more of user's lack of understanding what logbook is doing in the background. I was wondering what can cause python introspection to be stuck.

`
    import sys
    from logbook import Flags

    with Flags(introspection=False):
        logbook.StreamHandler(sys.stdout).push_application()
        logger = logbook.Logger('mylog')
        logger.info('Hello World')
        logger.debug('Buggy')
`
If you are using PyCharm, you can replicate it by inserting a breakpoint on  logger = logbook.Logger('mylog') to see the wait.

**Comment by vmalloc** [comment]
I can't think of anything that happens "in the background" when you initialize a logger or a handler, even more so a StreamHandler. Logbook doesn't do anything in the background except for when using queueing handlers. From first glance this looks like an environment issue. 

However, you can add a signal handler to print out the stacks of all running threads (e.g. SIGUSR1) and then send it when it gets stuck to see what your process is doing at the moment...

**Comment by runflowcode** [comment]
Hi,

First, I tried what you have suggested which was to add a signal handler for SIGUR1, and see what are the running process/thread is doing at the moment. But, PyCharm was experiencing the same issue, and that kinda rules out the possibility that it was from logbook package. 

So, for anyone experiencing the similar issue with PyCharm, the solution is to enable gevent.

There's an option within PyCharm to enable gevent. When I enable it, it was able to display debugger properly.

File > Settings > Build, Execution, Deployment > Python Debugger > Gevent compatible
