### ISSUE TITLE
how to format string like  %(levelname)-5s

### ISSUE THREAD

**Issue by honorcao** [getlogbook/logbook#267]
in logging,I can format string like %(levelname)-5s
but in logbook, how to do it.
I find {record.time:%Y-%m-%d %H:%M:%S}  this can format time success
but I try {record.level_name:%5s} ,it happen an error

**Comment by vmalloc** [comment]
See https://kapeli.com/cheat_sheets/Python_Format_Strings.docset/Contents/Resources/Documents/index for specific examples you can use. Logbook uses the new-style formatting feature as it is, so all those should work.

If you want to format with spaces, you should do `{record.level_name:<5}` or `{record.level_name:5}`
