### ISSUE TITLE
No documentation for JSON log format

### ISSUE THREAD

**Issue by naviens** [getlogbook/logbook#279]
How can i integrate logbook with python json logger,
`https://github.com/madzak/python-json-logger`

**Comment by vmalloc** [comment]
This is not a core functionality of Logbook - it should be done by implementing a handler (3rd party or in your own code) to emit the required format...

You can take a look at the existing handlers and their formatting logic to get a hint of how to do it in Logbook -- we don't have better documentation on how to write handlers at the moment.

Having said that, we're always open to PRs adding missing docs!
