### ISSUE TITLE
Use of `datetime.utcfromtimestamp()` on 3.12+ is also deprecated

### ISSUE THREAD

**Issue by slothkong** [getlogbook/logbook#384]
Hello there,

Although as of 1.7.0, deprecation of `datetime.utcnow()`  was delt with by @RazerM ( 5273fa2 ), it seems like `datetime.utcfromtimestamp()` also requires some attention.

The [official datetime docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp) point out:

> **Warning**: Because naive `datetime` objects are treated by many `datetime` methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing a specific timestamp in UTC is by calling `datetime.fromtimestamp(timestamp, tz=timezone.utc)`. 

For context, stumbled upon the deprecation warning while unittesting `dbt-core`, as part of [issue 9791](https://github.com/dbt-labs/dbt-core/issues/9791). When drilling down the logs, ended up at:

https://github.com/getlogbook/logbook/blob/e7cc074e6a7affa86c033efb08591e59356d65b9/src/logbook/compat.py#L143

**Comment by slothkong** [comment]
I put up a [tiny pull request](https://github.com/getlogbook/logbook/pull/385) to address the deprecation warnings, hopefully as part of the next minor release 🤞

Any feedback is more than welcomed~

**Comment by RazerM** [comment]
Forgot to close this, fixed in 1.8
