### ISSUE TITLE
Colors on Windows

### ISSUE THREAD

**Issue by asmeurer** [getlogbook/logbook#98]
How do you feel about using https://pypi.python.org/pypi/colorama to make the colorized handler work on Windows? It can be made into a dependency on Windows for that part of the code, or the relevant parts of the code copied over to _termcolors.py (it's BSD licensed).

**Comment by brainstorm** [comment]
I'm fine with that as long as it is portable and configurable, @vmalloc?

**Comment by vmalloc** [comment]
I'm also fine with using Colorama, but we need people to help test it on Windows - our CI doesn't do that and I myself am not using Windows...

**Comment by RazerM** [comment]
The problem I see is that `ColorizedStderrHandler` claims to use `sys.stdout` even when it changes, so if we wrapped `sys.stdout` then the colours wouldn't work if sys.stdout changed.

We could make `ColorizedStreamHandler` which uses colorama to wrap `self.stream` after `StreamHandler.__init__`.

Other than that, perhaps it's easiest to add a note to the documentation that Windows need to import and initialise colorama.

**Comment by brainstorm** [comment]
@asmeurer, happy to receive and review a pullrequest on that if you wish to implement it :+1:

**Comment by asmeurer** [comment]
I can't remember what I was originally using this for, but I'm not currently using logbook (or Windows for that matter). Someone else may end up doing it, though.

**Comment by RazerM** [comment]
I'm going to submit a pull request for this soon.
